name: Measure code coverage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Build with Maven
        run: mvn clean verify --file ./passik/pom.xml

      - name: Upload JaCoCo Report Artifact
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: code-coverage/target/site/jacoco-aggregate/index.html

      - name: Publish coverage report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.CODE_COVERAGE_TOKEN }}
          publish_dir: ./code-coverage/target/site/jacoco-aggregate
